on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          settings-path: ${{ github.workspace }}
      - name: build with maven
        run: mvn -B package --file pom.xml
      - if: github.event.release
        name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
      - name: Configure GPG Key
        run: |
            mkdir -p ~/.gnupg/
            chown -R $(whoami) ~/.gnupg/
            chmod 600 ~/.gnupg/*
            chmod 700 ~/.gnupg
            printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
            gpg --import --no-tty --batch --yes ~/.gnupg/private.key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - if: github.event.release
        name: Release Maven Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -P release
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

